# Generated by Django 3.1.7 on 2021-03-10 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('pickup_add', models.CharField(blank=True, max_length=200)),
                ('pickup_name', models.CharField(max_length=100)),
                ('pickup_phone', models.CharField(blank=True, max_length=30)),
                ('drop_add', models.CharField(blank=True, max_length=200)),
                ('recipient_name', models.CharField(max_length=100)),
                ('recipient_phone', models.CharField(blank=True, max_length=30)),
                ('order_details', models.TextField()),
            ],
        ),
    ]
