# Generated by Django 3.1.7 on 2021-03-11 19:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='drop_add',
            new_name='dropoff_address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='pickup_add',
            new_name='pickup_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AddField(
            model_name='order',
            name='submitted',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
